import streamlit as st
import requests

# GEMINI API 키 가져오기
gemini_api_key = st.secrets["AIzaSyBSWxrPAa0lV3YA_Rpy31VPwboZb1FmqSA"]["gemini"]

# API 호출
url = "https://api.gemini.com/v1/some-endpoint"
headers = {"Authorization": f"Bearer {gemini_api_key}"}
response = requests.get(url, headers=headers)

# 결과 출력
st.write("API Response:", response.json())
